//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precios
    {
        public int IDPrecio { get; set; }
        public string Nombre { get; set; }
        public decimal ValorDia { get; set; }
        public decimal ValorSemana { get; set; }
        public decimal ValorQuincena { get; set; }
        public decimal ValorMes { get; set; }
        public System.DateTime VigenciaDesde { get; set; }
        public System.DateTime VigenciaHasta { get; set; }
        public int IDListaPrecio { get; set; }
    
        public virtual ListasPrecio ListasPrecio { get; set; }
    }
}
