//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zonas
    {
        public Zonas()
        {
            this.Propiedades = new HashSet<Propiedades>();
        }
    
        public int IDZona { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Propiedades> Propiedades { get; set; }
    }
}
